security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator

            logout:
                path: app_logout
                target: /

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 7 jours
                path: /

    access_control:
        # Accès public aux routes de connexion / inscription
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }

        # Les routes admin : seuls les admins peuvent y accéder
        - { path: ^/joueur, roles: ROLE_ADMIN }
        - { path: ^/entraineur, roles : ROLE_ADMIN }
        - { path: ^/rencontre, roles: ROLE_ADMIN }
        - { path: ^/seance, roles: ROLE_ADMIN }
        - { path: ^/composition, roles: ROLE_ADMIN }
        - { path: ^//entraineur/dashboard, roles: ROLe_ENTRAINEUR }

        # Tout le reste : utilisateur connecté (ROLE_USER minimum)
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3 memory_cost: 10
