security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator

            logout:
                path: app_logout
                target: /

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        # Public routes
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }

        # Routes accessibles à l'entraîneur uniquement
        - { path: ^/dashboard, roles: ROLE_ENTRAINEUR }
        #- { path: ^/entraineur, roles: ROLE_ENTRAINEUR }

        # Routes accessibles à l'admin uniquement
        - { path: ^/rencontre, roles: ROLE_ADMIN }
        - { path: ^/seance, roles: ROLE_ADMIN }

        # Routes partagées entre entraîneur et admin
        - { path: ^/joueur, roles: [ROLE_ENTRAINEUR, ROLE_ADMIN] }
        - { path: ^/composition, roles: [ROLE_ENTRAINEUR, ROLE_ADMIN] }
        - { path: ^/entraineur, roles: [ROLE_ENTRAINEUR, ROLE_ADMIN]  }

        # Catch-all si besoin
        # - { path: ^/, roles: ROLE_USER }
